name = "typemeteor"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[env.development]
name = "typemeteor-worker-dev"
vars = { ENVIRONMENT = "development" }

[[d1_databases]]
binding = "DB"
database_name = "typemeteor-db"
database_id = "b9b7e435-8508-47a9-bfc2-133018ed975a"